#!/bin/bash -l
#SBATCH -D /home/makman/ProSNP/mapping/
#SBATCH -J RG16
#SBATCH -o /home/makman/ProSNP/outs/readGroups16.out
#SBATCH -e /home/makman/ProSNP/outs/readGroups16.err
#SBATCH --mail-type=All
#SBATCH --mail-user=makman@berkeley.edu
#SBATCH -p bigmemm
#SBATCH --mem=72GB
#SBATCH --time=400:00:00
module load picardtools/2.7.1
module load java

# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_ALC_1045_markDups.bam O=ProSNP12_ALC_1045_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_ALC_1045 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_ALC_12_markDups.bam O=ProSNP12_ALC_12_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_ALC_12 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_ALC_34_markDups.bam O=ProSNP12_ALC_34_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_ALC_34 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_ALC_44_markDups.bam O=ProSNP12_ALC_44_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_ALC_44 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_ANY_19_markDups.bam O=ProSNP12_ANY_19_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_ANY_19 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_ANY_1_markDups.bam O=ProSNP12_ANY_1_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_ANY_1 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_ANY_30_markDups.bam O=ProSNP12_ANY_30_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_ANY_30 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_BAN_21_markDups.bam O=ProSNP12_BAN_21_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_BAN_21 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_BAN_35_markDups.bam O=ProSNP12_BAN_35_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_BAN_35 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_BAN_3_markDups.bam O=ProSNP12_BAN_3_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_BAN_3 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_BAV_20_markDups.bam O=ProSNP12_BAV_20_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_BAV_20 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_BAV_32_markDups.bam O=ProSNP12_BAV_32_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_BAV_32 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_BAV_44_markDups.bam O=ProSNP12_BAV_44_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_BAV_44 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_BRD_1_markDups.bam O=ProSNP12_BRD_1_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_BRD_1 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_BRD_22_markDups.bam O=ProSNP12_BRD_22_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_BRD_22 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_BRD_41_markDups.bam O=ProSNP12_BRD_41_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_BRD_41 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_CDB_26_markDups.bam O=ProSNP12_CDB_26_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_CDB_26 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_CDB_2_markDups.bam O=ProSNP12_CDB_2_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_CDB_2 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_CDB_40_markDups.bam O=ProSNP12_CDB_40_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_CDB_40 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_CER_1_markDups.bam O=ProSNP12_CER_1_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_CER_1 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_CER_22_markDups.bam O=ProSNP12_CER_22_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_CER_22 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_CER_42_markDups.bam O=ProSNP12_CER_42_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_CER_42 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_GAR_1_markDups.bam O=ProSNP12_GAR_1_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_GAR_1 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_GAR_20_markDups.bam O=ProSNP12_GAR_20_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_GAR_20 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_GAR_41_markDups.bam O=ProSNP12_GAR_41_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_GAR_41 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_KAR_1_markDups.bam O=ProSNP12_KAR_1_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_KAR_1 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_KAR_25_markDups.bam O=ProSNP12_KAR_25_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_KAR_25 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_KAR_42_markDups.bam O=ProSNP12_KAR_42_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_KAR_42 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_KLM_20_markDups.bam O=ProSNP12_KLM_20_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_KLM_20 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_KLM_45_markDups.bam O=ProSNP12_KLM_45_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_KLM_45 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_KLM_5_markDups.bam O=ProSNP12_KLM_5_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_KLM_5 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_KSW_20_markDups.bam O=ProSNP12_KSW_20_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_KSW_20 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_KSW_45_markDups.bam O=ProSNP12_KSW_45_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_KSW_45 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_KSW_4_markDups.bam O=ProSNP12_KSW_4_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_KSW_4 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_LOE_1_markDups.bam O=ProSNP12_LOE_1_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_LOE_1 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_LOE_23_markDups.bam O=ProSNP12_LOE_23_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_LOE_23 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_LOE_45_markDups.bam O=ProSNP12_LOE_45_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_LOE_45 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_MGU_17_markDups.bam O=ProSNP12_MGU_17_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_MGU_17 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_MGU_1_markDups.bam O=ProSNP12_MGU_1_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_MGU_1 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_MGU_57_markDups.bam O=ProSNP12_MGU_57_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_MGU_57 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_POT_1_markDups.bam O=ProSNP12_POT_1_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_POT_1 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_POT_26_markDups.bam O=ProSNP12_POT_26_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_POT_26 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_POT_44_markDups.bam O=ProSNP12_POT_44_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_POT_44 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_RIV_21_markDups.bam O=ProSNP12_RIV_21_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_RIV_21 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_RIV_2_markDups.bam O=ProSNP12_RIV_2_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_RIV_2 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_RIV_40_markDups.bam O=ProSNP12_RIV_40_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_RIV_40 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_RND_1_markDups.bam O=ProSNP12_RND_1_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_RND_1 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_RND_20_markDups.bam O=ProSNP12_RND_20_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_RND_20 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_RND_44_markDups.bam O=ProSNP12_RND_44_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_RND_44 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_SWA_1_markDups.bam O=ProSNP12_SWA_1_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_SWA_1 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_SWA_20_markDups.bam O=ProSNP12_SWA_20_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_SWA_20 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_SWA_45_markDups.bam O=ProSNP12_SWA_45_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_SWA_45 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_UNI_1_markDups.bam O=ProSNP12_UNI_1_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_UNI_1 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_UNI_24_markDups.bam O=ProSNP12_UNI_24_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_UNI_24 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_UNI_39_markDups.bam O=ProSNP12_UNI_39_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_UNI_39 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_VAN_15_markDups.bam O=ProSNP12_VAN_15_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_VAN_15 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_VAN_29_markDups.bam O=ProSNP12_VAN_29_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_VAN_29 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP12_VAN_2_markDups.bam O=ProSNP12_VAN_2_markDups_RG.bam RGPL=Illumina RGPU=ProSNP12 RGLB=SinhaLab RGSM=ProSNP12_VAN_2 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_ALC_1109_markDups.bam O=ProSNP4_ALC_1109_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_ALC_1109 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_ALC_1132_markDups.bam O=ProSNP4_ALC_1132_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_ALC_1132 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_ALC_314_markDups.bam O=ProSNP4_ALC_314_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_ALC_314 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_ALC_573_markDups.bam O=ProSNP4_ALC_573_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_ALC_573 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_ANY_111_markDups.bam O=ProSNP4_ANY_111_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_ANY_111 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_ANY_1152_markDups.bam O=ProSNP4_ANY_1152_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_ANY_1152 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_ANY_300_markDups.bam O=ProSNP4_ANY_300_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_ANY_300 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_ANY_39_markDups.bam O=ProSNP4_ANY_39_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_ANY_39 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_ANY_507_markDups.bam O=ProSNP4_ANY_507_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_ANY_507 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_BAN_1060_markDups.bam O=ProSNP4_BAN_1060_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_BAN_1060 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_BAN_133_markDups.bam O=ProSNP4_BAN_133_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_BAN_133 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_BAN_200_markDups.bam O=ProSNP4_BAN_200_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_BAN_200 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_BAN_385_markDups.bam O=ProSNP4_BAN_385_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_BAN_385 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_BAV_1014_markDups.bam O=ProSNP4_BAV_1014_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_BAV_1014 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_BAV_1022_markDups.bam O=ProSNP4_BAV_1022_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_BAV_1022 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_BAV_22_markDups.bam O=ProSNP4_BAV_22_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_BAV_22 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_BAV_337_markDups.bam O=ProSNP4_BAV_337_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_BAV_337 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_BAV_448_markDups.bam O=ProSNP4_BAV_448_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_BAV_448 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_BRD_1215_markDups.bam O=ProSNP4_BRD_1215_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_BRD_1215 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_BRD_123_markDups.bam O=ProSNP4_BRD_123_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_BRD_123 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_BRD_356_markDups.bam O=ProSNP4_BRD_356_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_BRD_356 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_BRD_406_markDups.bam O=ProSNP4_BRD_406_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_BRD_406 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_BRD_513_markDups.bam O=ProSNP4_BRD_513_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_BRD_513 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_CDB_1100_markDups.bam O=ProSNP4_CDB_1100_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_CDB_1100 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_CDB_252_markDups.bam O=ProSNP4_CDB_252_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_CDB_252 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_CDB_28_markDups.bam O=ProSNP4_CDB_28_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_CDB_28 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_CDB_440_markDups.bam O=ProSNP4_CDB_440_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_CDB_440 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_CDB_567_markDups.bam O=ProSNP4_CDB_567_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_CDB_567 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_CER_1023_markDups.bam O=ProSNP4_CER_1023_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_CER_1023 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_CER_291_markDups.bam O=ProSNP4_CER_291_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_CER_291 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_CER_39_markDups.bam O=ProSNP4_CER_39_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_CER_39 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_CER_445_markDups.bam O=ProSNP4_CER_445_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_CER_445 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_CER_50_markDups.bam O=ProSNP4_CER_50_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_CER_50 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_GAR_11_markDups.bam O=ProSNP4_GAR_11_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_GAR_11 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_GAR_259_markDups.bam O=ProSNP4_GAR_259_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_GAR_259 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_GAR_298_markDups.bam O=ProSNP4_GAR_298_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_GAR_298 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_GAR_309_markDups.bam O=ProSNP4_GAR_309_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_GAR_309 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_GAR_574_markDups.bam O=ProSNP4_GAR_574_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_GAR_574 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_KAR_1004_markDups.bam O=ProSNP4_KAR_1004_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_KAR_1004 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_KAR_1159_markDups.bam O=ProSNP4_KAR_1159_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_KAR_1159 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_KAR_288_markDups.bam O=ProSNP4_KAR_288_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_KAR_288 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_KAR_57_markDups.bam O=ProSNP4_KAR_57_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_KAR_57 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_KAR_596_markDups.bam O=ProSNP4_KAR_596_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_KAR_596 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_KLM_1112_markDups.bam O=ProSNP4_KLM_1112_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_KLM_1112 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_KLM_1209_markDups.bam O=ProSNP4_KLM_1209_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_KLM_1209 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_KLM_519_markDups.bam O=ProSNP4_KLM_519_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_KLM_519 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_KLM_6_markDups.bam O=ProSNP4_KLM_6_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_KLM_6 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_KLM_9_markDups.bam O=ProSNP4_KLM_9_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_KLM_9 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_KSW_1047_markDups.bam O=ProSNP4_KSW_1047_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_KSW_1047 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_KSW_1064_markDups.bam O=ProSNP4_KSW_1064_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_KSW_1064 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_KSW_106_markDups.bam O=ProSNP4_KSW_106_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_KSW_106 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_KSW_1163_markDups.bam O=ProSNP4_KSW_1163_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_KSW_1163 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_KSW_1206_markDups.bam O=ProSNP4_KSW_1206_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_KSW_1206 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_KSW_132_markDups.bam O=ProSNP4_KSW_132_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_KSW_132 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_KSW_18_markDups.bam O=ProSNP4_KSW_18_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_KSW_18 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_LOE_1033_markDups.bam O=ProSNP4_LOE_1033_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_LOE_1033 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_LOE_1141_markDups.bam O=ProSNP4_LOE_1141_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_LOE_1141 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_LOE_359_markDups.bam O=ProSNP4_LOE_359_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_LOE_359 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_LOE_404_markDups.bam O=ProSNP4_LOE_404_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_LOE_404 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_LOE_82_markDups.bam O=ProSNP4_LOE_82_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_LOE_82 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_MGU_135_markDups.bam O=ProSNP4_MGU_135_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_MGU_135 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_MGU_214_markDups.bam O=ProSNP4_MGU_214_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_MGU_214 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_MGU_295_markDups.bam O=ProSNP4_MGU_295_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_MGU_295 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_MGU_407_markDups.bam O=ProSNP4_MGU_407_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_MGU_407 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_POT_1005_markDups.bam O=ProSNP4_POT_1005_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_POT_1005 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_POT_1188_markDups.bam O=ProSNP4_POT_1188_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_POT_1188 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_POT_126_markDups.bam O=ProSNP4_POT_126_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_POT_126 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_POT_313_markDups.bam O=ProSNP4_POT_313_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_POT_313 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_POT_531_markDups.bam O=ProSNP4_POT_531_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_POT_531 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_RIV_108_markDups.bam O=ProSNP4_RIV_108_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_RIV_108 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_RIV_1103_markDups.bam O=ProSNP4_RIV_1103_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_RIV_1103 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_RIV_1205_markDups.bam O=ProSNP4_RIV_1205_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_RIV_1205 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_RIV_15_markDups.bam O=ProSNP4_RIV_15_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_RIV_15 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_RIV_193_markDups.bam O=ProSNP4_RIV_193_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_RIV_193 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_RND_124_markDups.bam O=ProSNP4_RND_124_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_RND_124 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_RND_147_markDups.bam O=ProSNP4_RND_147_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_RND_147 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_RND_261_markDups.bam O=ProSNP4_RND_261_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_RND_261 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_RND_318_markDups.bam O=ProSNP4_RND_318_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_RND_318 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_RND_420_markDups.bam O=ProSNP4_RND_420_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_RND_420 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_RND_576_markDups.bam O=ProSNP4_RND_576_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_RND_576 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_SWA_112_markDups.bam O=ProSNP4_SWA_112_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_SWA_112 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_SWA_1183_markDups.bam O=ProSNP4_SWA_1183_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_SWA_1183 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_SWA_13_markDups.bam O=ProSNP4_SWA_13_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_SWA_13 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_SWA_352_markDups.bam O=ProSNP4_SWA_352_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_SWA_352 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_SWA_545_markDups.bam O=ProSNP4_SWA_545_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_SWA_545 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_UNI_1217_markDups.bam O=ProSNP4_UNI_1217_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_UNI_1217 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_UNI_306_markDups.bam O=ProSNP4_UNI_306_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_UNI_306 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_UNI_347_markDups.bam O=ProSNP4_UNI_347_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_UNI_347 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_UNI_383_markDups.bam O=ProSNP4_UNI_383_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_UNI_383 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_UNI_544_markDups.bam O=ProSNP4_UNI_544_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_UNI_544 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_UNI_55_markDups.bam O=ProSNP4_UNI_55_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_UNI_55 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_VAN_1158_markDups.bam O=ProSNP4_VAN_1158_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_VAN_1158 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_VAN_1211_markDups.bam O=ProSNP4_VAN_1211_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_VAN_1211 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_VAN_293_markDups.bam O=ProSNP4_VAN_293_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_VAN_293 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_VAN_361_markDups.bam O=ProSNP4_VAN_361_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_VAN_361 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP4_VAN_521_markDups.bam O=ProSNP4_VAN_521_markDups_RG.bam RGPL=Illumina RGPU=ProSNP4 RGLB=SinhaLab RGSM=ProSNP4_VAN_521 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_ALC1045_markDups.bam O=ProSNP5_ALC1045_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_ALC1045 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_ALC230_markDups.bam O=ProSNP5_ALC230_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_ALC230 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_ALC250_markDups.bam O=ProSNP5_ALC250_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_ALC250 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_ALC502_markDups.bam O=ProSNP5_ALC502_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_ALC502 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_ALC62_markDups.bam O=ProSNP5_ALC62_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_ALC62 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_ANY1126_markDups.bam O=ProSNP5_ANY1126_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_ANY1126 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_ANY116_markDups.bam O=ProSNP5_ANY116_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_ANY116 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_ANY117_markDups.bam O=ProSNP5_ANY117_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_ANY117 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_ANY303_markDups.bam O=ProSNP5_ANY303_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_ANY303 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_ANY322_markDups.bam O=ProSNP5_ANY322_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_ANY322 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_BAN1138_markDups.bam O=ProSNP5_BAN1138_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_BAN1138 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_BAN207_markDups.bam O=ProSNP5_BAN207_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_BAN207 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_BAN229_markDups.bam O=ProSNP5_BAN229_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_BAN229 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_BAN506_markDups.bam O=ProSNP5_BAN506_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_BAN506 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_BAN92_markDups.bam O=ProSNP5_BAN92_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_BAN92 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_BAV1191_markDups.bam O=ProSNP5_BAV1191_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_BAV1191 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_BAV422_markDups.bam O=ProSNP5_BAV422_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_BAV422 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_BAV527_markDups.bam O=ProSNP5_BAV527_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_BAV527 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_BAV75_markDups.bam O=ProSNP5_BAV75_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_BAV75 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_BAV7_markDups.bam O=ProSNP5_BAV7_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_BAV7 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_BRD369_markDups.bam O=ProSNP5_BRD369_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_BRD369 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_BRD381_markDups.bam O=ProSNP5_BRD381_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_BRD381 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_BRD483_markDups.bam O=ProSNP5_BRD483_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_BRD483 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_BRD484_markDups.bam O=ProSNP5_BRD484_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_BRD484 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_BRD51_markDups.bam O=ProSNP5_BRD51_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_BRD51 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_CDB100_markDups.bam O=ProSNP5_CDB100_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_CDB100 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_CDB1134_markDups.bam O=ProSNP5_CDB1134_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_CDB1134 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_CDB376_markDups.bam O=ProSNP5_CDB376_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_CDB376 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_CDB512_markDups.bam O=ProSNP5_CDB512_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_CDB512 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_CDB564_markDups.bam O=ProSNP5_CDB564_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_CDB564 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_CER1117_markDups.bam O=ProSNP5_CER1117_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_CER1117 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_CER2_markDups.bam O=ProSNP5_CER2_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_CER2 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_CER382_markDups.bam O=ProSNP5_CER382_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_CER382 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_CER458_markDups.bam O=ProSNP5_CER458_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_CER458 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_CER78_markDups.bam O=ProSNP5_CER78_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_CER78 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_GAR1019_markDups.bam O=ProSNP5_GAR1019_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_GAR1019 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_GAR434_markDups.bam O=ProSNP5_GAR434_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_GAR434 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_GAR439_markDups.bam O=ProSNP5_GAR439_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_GAR439 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_GAR46_markDups.bam O=ProSNP5_GAR46_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_GAR46 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_GAR547_markDups.bam O=ProSNP5_GAR547_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_GAR547 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_KAR1044_markDups.bam O=ProSNP5_KAR1044_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_KAR1044 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_KAR1063_markDups.bam O=ProSNP5_KAR1063_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_KAR1063 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_KAR122_markDups.bam O=ProSNP5_KAR122_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_KAR122 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_KAR178_markDups.bam O=ProSNP5_KAR178_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_KAR178 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_KAR346_markDups.bam O=ProSNP5_KAR346_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_KAR346 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_KLM1025_markDups.bam O=ProSNP5_KLM1025_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_KLM1025 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_KLM1203_markDups.bam O=ProSNP5_KLM1203_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_KLM1203 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_KLM534_markDups.bam O=ProSNP5_KLM534_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_KLM534 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_KLM56_markDups.bam O=ProSNP5_KLM56_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_KLM56 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_KLM97_markDups.bam O=ProSNP5_KLM97_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_KLM97 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_KSW1145_markDups.bam O=ProSNP5_KSW1145_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_KSW1145 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_KSW1206_markDups.bam O=ProSNP5_KSW1206_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_KSW1206 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_KSW398_markDups.bam O=ProSNP5_KSW398_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_KSW398 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_KSW505_markDups.bam O=ProSNP5_KSW505_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_KSW505 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_KSW597_markDups.bam O=ProSNP5_KSW597_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_KSW597 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_KSW95_markDups.bam O=ProSNP5_KSW95_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_KSW95 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_LOE1018_markDups.bam O=ProSNP5_LOE1018_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_LOE1018 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_LOE125_markDups.bam O=ProSNP5_LOE125_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_LOE125 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_LOE388_markDups.bam O=ProSNP5_LOE388_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_LOE388 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_LOE585_markDups.bam O=ProSNP5_LOE585_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_LOE585 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_LOE79_markDups.bam O=ProSNP5_LOE79_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_LOE79 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_MGU1006_markDups.bam O=ProSNP5_MGU1006_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_MGU1006 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_MGU1056_markDups.bam O=ProSNP5_MGU1056_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_MGU1056 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_MGU16_markDups.bam O=ProSNP5_MGU16_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_MGU16 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_MGU490_markDups.bam O=ProSNP5_MGU490_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_MGU490 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_MGU498_markDups.bam O=ProSNP5_MGU498_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_MGU498 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_POT1176_markDups.bam O=ProSNP5_POT1176_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_POT1176 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_POT255_markDups.bam O=ProSNP5_POT255_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_POT255 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_POT282_markDups.bam O=ProSNP5_POT282_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_POT282 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_POT525_markDups.bam O=ProSNP5_POT525_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_POT525 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_POT54_markDups.bam O=ProSNP5_POT54_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_POT54 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_RIV151_markDups.bam O=ProSNP5_RIV151_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_RIV151 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_RIV191_markDups.bam O=ProSNP5_RIV191_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_RIV191 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_RIV195_markDups.bam O=ProSNP5_RIV195_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_RIV195 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_RIV44_markDups.bam O=ProSNP5_RIV44_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_RIV44 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_RIV560_markDups.bam O=ProSNP5_RIV560_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_RIV560 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_RND1010_markDups.bam O=ProSNP5_RND1010_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_RND1010 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_RND1210_markDups.bam O=ProSNP5_RND1210_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_RND1210 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_RND139_markDups.bam O=ProSNP5_RND139_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_RND139 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_RND290_markDups.bam O=ProSNP5_RND290_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_RND290 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_RND579_markDups.bam O=ProSNP5_RND579_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_RND579 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_SWA107_markDups.bam O=ProSNP5_SWA107_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_SWA107 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_SWA157_markDups.bam O=ProSNP5_SWA157_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_SWA157 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_SWA189_markDups.bam O=ProSNP5_SWA189_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_SWA189 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_SWA577_markDups.bam O=ProSNP5_SWA577_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_SWA577 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_SWA80_markDups.bam O=ProSNP5_SWA80_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_SWA80 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_UNI1001_markDups.bam O=ProSNP5_UNI1001_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_UNI1001 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_UNI386_markDups.bam O=ProSNP5_UNI386_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_UNI386 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_UNI3_markDups.bam O=ProSNP5_UNI3_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_UNI3 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_UNI403_markDups.bam O=ProSNP5_UNI403_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_UNI403 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_VAN163_markDups.bam O=ProSNP5_VAN163_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_VAN163 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_VAN206_markDups.bam O=ProSNP5_VAN206_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_VAN206 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_VAN208_markDups.bam O=ProSNP5_VAN208_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_VAN208 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_VAN260_markDups.bam O=ProSNP5_VAN260_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_VAN260 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP5_VAN27_markDups.bam O=ProSNP5_VAN27_markDups_RG.bam RGPL=Illumina RGPU=ProSNP5 RGLB=SinhaLab RGSM=ProSNP5_VAN27 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_ANY_1020_markDups.bam O=ProSNP6_ANY_1020_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_ANY_1020 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_ANY_1079_markDups.bam O=ProSNP6_ANY_1079_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_ANY_1079 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_ANY_1122_markDups.bam O=ProSNP6_ANY_1122_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_ANY_1122 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_ANY_12_markDups.bam O=ProSNP6_ANY_12_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_ANY_12 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_ANY_301_markDups.bam O=ProSNP6_ANY_301_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_ANY_301 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_ANY_518_markDups.bam O=ProSNP6_ANY_518_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_ANY_518 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_ANY_85_markDups.bam O=ProSNP6_ANY_85_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_ANY_85 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_BAV_1077_markDups.bam O=ProSNP6_BAV_1077_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_BAV_1077 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_BAV_1214_markDups.bam O=ProSNP6_BAV_1214_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_BAV_1214 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_BAV_339_markDups.bam O=ProSNP6_BAV_339_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_BAV_339 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_BAV_462_markDups.bam O=ProSNP6_BAV_462_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_BAV_462 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_BAV_556_markDups.bam O=ProSNP6_BAV_556_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_BAV_556 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_BAV_63_markDups.bam O=ProSNP6_BAV_63_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_BAV_63 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_BRD_1009_markDups.bam O=ProSNP6_BRD_1009_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_BRD_1009 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_BRD_342_markDups.bam O=ProSNP6_BRD_342_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_BRD_342 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_BRD_442_markDups.bam O=ProSNP6_BRD_442_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_BRD_442 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_BRD_501_markDups.bam O=ProSNP6_BRD_501_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_BRD_501 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_BRD_533_markDups.bam O=ProSNP6_BRD_533_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_BRD_533 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_BRD_543_markDups.bam O=ProSNP6_BRD_543_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_BRD_543 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_CDB_228_markDups.bam O=ProSNP6_CDB_228_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_CDB_228 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_CDB_571_markDups.bam O=ProSNP6_CDB_571_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_CDB_571 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_CER_1038_markDups.bam O=ProSNP6_CER_1038_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_CER_1038 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_CER_1142_markDups.bam O=ProSNP6_CER_1142_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_CER_1142 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_CER_14_markDups.bam O=ProSNP6_CER_14_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_CER_14 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_CER_199_markDups.bam O=ProSNP6_CER_199_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_CER_199 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_CER_338_markDups.bam O=ProSNP6_CER_338_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_CER_338 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_CER_589_markDups.bam O=ProSNP6_CER_589_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_CER_589 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_GAR_1041_markDups.bam O=ProSNP6_GAR_1041_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_GAR_1041 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_GAR_1200_markDups.bam O=ProSNP6_GAR_1200_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_GAR_1200 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_GAR_174_markDups.bam O=ProSNP6_GAR_174_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_GAR_174 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_GAR_299_markDups.bam O=ProSNP6_GAR_299_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_GAR_299 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_GAR_437_markDups.bam O=ProSNP6_GAR_437_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_GAR_437 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_GAR_557_markDups.bam O=ProSNP6_GAR_557_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_GAR_557 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_GAR_90_markDups.bam O=ProSNP6_GAR_90_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_GAR_90 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KAR_1187_markDups.bam O=ProSNP6_KAR_1187_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KAR_1187 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KAR_184_markDups.bam O=ProSNP6_KAR_184_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KAR_184 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KAR_486_markDups.bam O=ProSNP6_KAR_486_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KAR_486 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KAR_49_markDups.bam O=ProSNP6_KAR_49_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KAR_49 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KAR_68_markDups.bam O=ProSNP6_KAR_68_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KAR_68 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KAR_84_markDups.bam O=ProSNP6_KAR_84_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KAR_84 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KLM_1052_markDups.bam O=ProSNP6_KLM_1052_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KLM_1052 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KLM_1129_markDups.bam O=ProSNP6_KLM_1129_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KLM_1129 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KLM_155_markDups.bam O=ProSNP6_KLM_155_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KLM_155 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KLM_343_markDups.bam O=ProSNP6_KLM_343_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KLM_343 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KLM_475_markDups.bam O=ProSNP6_KLM_475_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KLM_475 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KLM_566_markDups.bam O=ProSNP6_KLM_566_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KLM_566 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KLM_582_markDups.bam O=ProSNP6_KLM_582_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KLM_582 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KSW_1043_markDups.bam O=ProSNP6_KSW_1043_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KSW_1043 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KSW_104_markDups.bam O=ProSNP6_KSW_104_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KSW_104 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KSW_1076_markDups.bam O=ProSNP6_KSW_1076_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KSW_1076 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KSW_10_markDups.bam O=ProSNP6_KSW_10_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KSW_10 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KSW_1125_markDups.bam O=ProSNP6_KSW_1125_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KSW_1125 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KSW_47_markDups.bam O=ProSNP6_KSW_47_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KSW_47 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_KSW_516_markDups.bam O=ProSNP6_KSW_516_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_KSW_516 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_LOE_1035_markDups.bam O=ProSNP6_LOE_1035_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_LOE_1035 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_LOE_1150_markDups.bam O=ProSNP6_LOE_1150_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_LOE_1150 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_LOE_211_markDups.bam O=ProSNP6_LOE_211_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_LOE_211 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_LOE_497_markDups.bam O=ProSNP6_LOE_497_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_LOE_497 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_LOE_548_markDups.bam O=ProSNP6_LOE_548_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_LOE_548 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_POT_1119_markDups.bam O=ProSNP6_POT_1119_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_POT_1119 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_POT_128_markDups.bam O=ProSNP6_POT_128_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_POT_128 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_POT_183_markDups.bam O=ProSNP6_POT_183_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_POT_183 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_POT_380_markDups.bam O=ProSNP6_POT_380_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_POT_380 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_POT_463_markDups.bam O=ProSNP6_POT_463_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_POT_463 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_POT_594_markDups.bam O=ProSNP6_POT_594_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_POT_594 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_RIV_1148_markDups.bam O=ProSNP6_RIV_1148_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_RIV_1148 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_RIV_180_markDups.bam O=ProSNP6_RIV_180_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_RIV_180 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_RIV_351_markDups.bam O=ProSNP6_RIV_351_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_RIV_351 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_RIV_461_markDups.bam O=ProSNP6_RIV_461_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_RIV_461 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_RIV_530_markDups.bam O=ProSNP6_RIV_530_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_RIV_530 
java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_RIV_88_markDups.bam O=ProSNP6_RIV_88_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_RIV_88 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_RND_1116_markDups.bam O=ProSNP6_RND_1116_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_RND_1116 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_RND_1220_markDups.bam O=ProSNP6_RND_1220_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_RND_1220 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_RND_164_markDups.bam O=ProSNP6_RND_164_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_RND_164 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_RND_272_markDups.bam O=ProSNP6_RND_272_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_RND_272 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_RND_523_markDups.bam O=ProSNP6_RND_523_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_RND_523 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_RND_65_markDups.bam O=ProSNP6_RND_65_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_RND_65 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_SWA_140_markDups.bam O=ProSNP6_SWA_140_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_SWA_140 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_SWA_19_markDups.bam O=ProSNP6_SWA_19_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_SWA_19 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_SWA_304_markDups.bam O=ProSNP6_SWA_304_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_SWA_304 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_SWA_317_markDups.bam O=ProSNP6_SWA_317_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_SWA_317 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_SWA_341_markDups.bam O=ProSNP6_SWA_341_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_SWA_341 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_SWA_515_markDups.bam O=ProSNP6_SWA_515_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_SWA_515 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_SWA_96_markDups.bam O=ProSNP6_SWA_96_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_SWA_96 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_UNI_1087_markDups.bam O=ProSNP6_UNI_1087_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_UNI_1087 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_UNI_1175_markDups.bam O=ProSNP6_UNI_1175_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_UNI_1175 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_UNI_1204_markDups.bam O=ProSNP6_UNI_1204_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_UNI_1204 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_UNI_470_markDups.bam O=ProSNP6_UNI_470_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_UNI_470 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_UNI_479_markDups.bam O=ProSNP6_UNI_479_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_UNI_479 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_UNI_546_markDups.bam O=ProSNP6_UNI_546_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_UNI_546 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_VAN_1015_markDups.bam O=ProSNP6_VAN_1015_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_VAN_1015 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_VAN_1179_markDups.bam O=ProSNP6_VAN_1179_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_VAN_1179 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_VAN_269_markDups.bam O=ProSNP6_VAN_269_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_VAN_269 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_VAN_396_markDups.bam O=ProSNP6_VAN_396_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_VAN_396 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_VAN_443_markDups.bam O=ProSNP6_VAN_443_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_VAN_443 
# java -Djava.io.tmpdir=/home/makman/temp/ -Xmx64G -jar /share/apps/picard-tools-2.7.1/picard.jar AddOrReplaceReadGroups I=ProSNP6_VAN_93_markDups.bam O=ProSNP6_VAN_93_markDups_RG.bam RGPL=Illumina RGPU=ProSNP6 RGLB=SinhaLab RGSM=ProSNP6_VAN_93 





